In [1]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from keras.datasets import mnist
import numpy as np
import pandas as pd

2023-02-16 05:03:35.313572: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-16 05:03:35.313613: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [2]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
concrete_data.shape

(1030, 9)

In [4]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] 
target = concrete_data['Strength']

In [7]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [8]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

##### Finally, the last step is to normalize the data by substracting the mean and dividing by the standard deviation.

In [9]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [10]:
n_cols = predictors_norm.shape[1]

In [11]:
x_train, x_val, y_train, y_val = train_test_split(predictors_norm, target, test_size=0.3, random_state=24, shuffle=True)

In [12]:
model = tf.keras.models.Sequential([
    layers.Dense(10, activation="relu", input_shape=(n_cols,)), 
    layers.Dense(10, activation="relu"),
    layers.Dense(10, activation="relu"),
    layers.Dense(10, activation="relu"),
    layers.Dense(1)
])

2023-02-16 05:05:06.235401: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-16 05:05:06.235811: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-16 05:05:06.236164: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-16 05:05:06.236510: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-02-16 05:05:06.236910: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-16 05:05:06.237016: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2023-02-16 05:05:06.237105: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2023-02-16 05:05:06.237190: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory
2023-02-16 05:05:06.237275: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory
2023-02-16 05:05:06.237362: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2023-02-16 05:05:06.237446: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory
2023-02-16 05:05:06.237531: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2023-02-16 05:05:06.237545: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-02-16 05:05:06.238274: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 10)                90

 dense_1 (Dense)             (None, 10)                110

 dense_2 (Dense)             (None, 10)                110

 dense_3 (Dense)             (None, 10)                110

 dense_4 (Dense)             (None, 1)                 11

=================================================================
Total params: 431
Trainable params: 431
Non-trainable params: 0
_________________________________________________________________

In [14]:
model.compile(optimizer='adam',
              loss='mean_squared_error')

In [15]:
print('x_train : ')
print(x_train.shape)
print('')
print('x_val : ')
print(x_val.shape)
print('')
print('')
print('y_train : ')
print(y_train.shape)
print('')
print('y_val : ')
print(y_val.shape)

x_train :
(721, 8)

x_val :
(309, 8)


y_train :
(721,)

y_val :
(309,)

In [16]:
history = model.fit(x_train, y_train, epochs=100, validation_data=(x_val, y_val))

Epoch 1/100
23/23 [==============================] - 1s 9ms/step - loss: 1585.7810 - val_loss: 1478.7244
Epoch 2/100
23/23 [==============================] - 0s 3ms/step - loss: 1559.5005 - val_loss: 1449.5309
Epoch 3/100
23/23 [==============================] - 0s 3ms/step - loss: 1523.3303 - val_loss: 1400.0763
Epoch 4/100
23/23 [==============================] - 0s 3ms/step - loss: 1456.4686 - val_loss: 1306.6064
Epoch 5/100
23/23 [==============================] - 0s 3ms/step - loss: 1333.1293 - val_loss: 1137.6613
Epoch 6/100
23/23 [==============================] - 0s 3ms/step - loss: 1118.7866 - val_loss: 865.1913
Epoch 7/100
23/23 [==============================] - 0s 3ms/step - loss: 805.1608 - val_loss: 531.1865
Epoch 8/100
23/23 [==============================] - 0s 3ms/step - loss: 486.9608 - val_loss: 303.8311
Epoch 9/100
23/23 [==============================] - 0s 3ms/step - loss: 314.4126 - val_loss: 244.6420
Epoch 10/100
23/23 [==============================] - 0s 3ms/step - loss: 249.9482 - val_loss: 223.1392
Epoch 11/100
23/23 [==============================] - 0s 3ms/step - loss: 224.5152 - val_loss: 210.6864
Epoch 12/100
23/23 [==============================] - 0s 3ms/step - loss: 211.3486 - val_loss: 201.5616
Epoch 13/100
23/23 [==============================] - 0s 3ms/step - loss: 202.0341 - val_loss: 192.9895
Epoch 14/100
23/23 [==============================] - 0s 3ms/step - loss: 195.2970 - val_loss: 188.4072
Epoch 15/100
23/23 [==============================] - 0s 2ms/step - loss: 188.8884 - val_loss: 180.2681
Epoch 16/100
23/23 [==============================] - 0s 3ms/step - loss: 182.1389 - val_loss: 177.7764
Epoch 17/100
23/23 [==============================] - 0s 3ms/step - loss: 178.0278 - val_loss: 171.4465
Epoch 18/100
23/23 [==============================] - 0s 3ms/step - loss: 173.5240 - val_loss: 165.7584
Epoch 19/100
23/23 [==============================] - 0s 3ms/step - loss: 168.9888 - val_loss: 163.4214
Epoch 20/100
23/23 [==============================] - 0s 3ms/step - loss: 165.2718 - val_loss: 161.2050
Epoch 21/100
23/23 [==============================] - 0s 3ms/step - loss: 162.0127 - val_loss: 156.9007
Epoch 22/100
23/23 [==============================] - 0s 3ms/step - loss: 159.4854 - val_loss: 154.3991
Epoch 23/100
23/23 [==============================] - 0s 3ms/step - loss: 157.0287 - val_loss: 150.7941
Epoch 24/100
23/23 [==============================] - 0s 3ms/step - loss: 154.2413 - val_loss: 150.8628
Epoch 25/100
23/23 [==============================] - 0s 3ms/step - loss: 152.2098 - val_loss: 147.5407
Epoch 26/100
23/23 [==============================] - 0s 3ms/step - loss: 150.0561 - val_loss: 146.1540
Epoch 27/100
23/23 [==============================] - 0s 3ms/step - loss: 148.7385 - val_loss: 142.8838
Epoch 28/100
23/23 [==============================] - 0s 3ms/step - loss: 146.9249 - val_loss: 142.6871
Epoch 29/100
23/23 [==============================] - 0s 3ms/step - loss: 144.6624 - val_loss: 140.7209
Epoch 30/100
23/23 [==============================] - 0s 3ms/step - loss: 143.1954 - val_loss: 138.8841
Epoch 31/100
23/23 [==============================] - 0s 3ms/step - loss: 142.2263 - val_loss: 137.8723
Epoch 32/100
23/23 [==============================] - 0s 3ms/step - loss: 140.4722 - val_loss: 138.3700
Epoch 33/100
23/23 [==============================] - 0s 3ms/step - loss: 139.3819 - val_loss: 135.5928
Epoch 34/100
23/23 [==============================] - 0s 3ms/step - loss: 137.9705 - val_loss: 134.3472
Epoch 35/100
23/23 [==============================] - 0s 3ms/step - loss: 136.4715 - val_loss: 133.2603
Epoch 36/100
23/23 [==============================] - 0s 3ms/step - loss: 135.3197 - val_loss: 132.5482
Epoch 37/100
23/23 [==============================] - 0s 3ms/step - loss: 134.1247 - val_loss: 131.5972
Epoch 38/100
23/23 [==============================] - 0s 3ms/step - loss: 133.9043 - val_loss: 130.8190
Epoch 39/100
23/23 [==============================] - 0s 3ms/step - loss: 131.9013 - val_loss: 128.4198
Epoch 40/100
23/23 [==============================] - 0s 3ms/step - loss: 131.0585 - val_loss: 129.0759
Epoch 41/100
23/23 [==============================] - 0s 3ms/step - loss: 130.0737 - val_loss: 127.5973
Epoch 42/100
23/23 [==============================] - 0s 3ms/step - loss: 128.9763 - val_loss: 126.4001
Epoch 43/100
23/23 [==============================] - 0s 3ms/step - loss: 127.6757 - val_loss: 125.6749
Epoch 44/100
23/23 [==============================] - 0s 3ms/step - loss: 126.6193 - val_loss: 123.9136
Epoch 45/100
23/23 [==============================] - 0s 3ms/step - loss: 126.1648 - val_loss: 123.9068
Epoch 46/100
23/23 [==============================] - 0s 3ms/step - loss: 123.7458 - val_loss: 121.1553
Epoch 47/100
23/23 [==============================] - 0s 3ms/step - loss: 123.3197 - val_loss: 121.5711
Epoch 48/100
23/23 [==============================] - 0s 3ms/step - loss: 121.8595 - val_loss: 119.3223
Epoch 49/100
23/23 [==============================] - 0s 3ms/step - loss: 119.4118 - val_loss: 117.0629
Epoch 50/100
23/23 [==============================] - 0s 3ms/step - loss: 118.1829 - val_loss: 116.3833
Epoch 51/100
23/23 [==============================] - 0s 3ms/step - loss: 116.5942 - val_loss: 114.3412
Epoch 52/100
23/23 [==============================] - 0s 3ms/step - loss: 114.8268 - val_loss: 114.4285
Epoch 53/100
23/23 [==============================] - 0s 3ms/step - loss: 112.9727 - val_loss: 111.2429
Epoch 54/100
23/23 [==============================] - 0s 3ms/step - loss: 110.8926 - val_loss: 110.0653
Epoch 55/100
23/23 [==============================] - 0s 3ms/step - loss: 108.8386 - val_loss: 108.4270
Epoch 56/100
23/23 [==============================] - 0s 3ms/step - loss: 107.2982 - val_loss: 106.6549
Epoch 57/100
23/23 [==============================] - 0s 3ms/step - loss: 104.6902 - val_loss: 103.9841
Epoch 58/100
23/23 [==============================] - 0s 3ms/step - loss: 102.5921 - val_loss: 101.7596
Epoch 59/100
23/23 [==============================] - 0s 3ms/step - loss: 100.6648 - val_loss: 99.7317
Epoch 60/100
23/23 [==============================] - 0s 3ms/step - loss: 97.9315 - val_loss: 98.1554
Epoch 61/100
23/23 [==============================] - 0s 3ms/step - loss: 96.0892 - val_loss: 94.9348
Epoch 62/100
23/23 [==============================] - 0s 3ms/step - loss: 93.3948 - val_loss: 92.6206
Epoch 63/100
23/23 [==============================] - 0s 3ms/step - loss: 91.0736 - val_loss: 90.2875
Epoch 64/100
23/23 [==============================] - 0s 3ms/step - loss: 88.9726 - val_loss: 87.8129
Epoch 65/100
23/23 [==============================] - 0s 3ms/step - loss: 86.2831 - val_loss: 86.1040
Epoch 66/100
23/23 [==============================] - 0s 3ms/step - loss: 84.5192 - val_loss: 83.2854
Epoch 67/100
23/23 [==============================] - 0s 3ms/step - loss: 82.5013 - val_loss: 81.8009
Epoch 68/100
23/23 [==============================] - 0s 3ms/step - loss: 81.0154 - val_loss: 79.7865
Epoch 69/100
23/23 [==============================] - 0s 3ms/step - loss: 78.4752 - val_loss: 78.2457
Epoch 70/100
23/23 [==============================] - 0s 3ms/step - loss: 76.8812 - val_loss: 75.9858
Epoch 71/100
23/23 [==============================] - 0s 3ms/step - loss: 75.1685 - val_loss: 74.7919
Epoch 72/100
23/23 [==============================] - 0s 3ms/step - loss: 74.5085 - val_loss: 72.5073
Epoch 73/100
23/23 [==============================] - 0s 3ms/step - loss: 72.4942 - val_loss: 72.5898
Epoch 74/100
23/23 [==============================] - 0s 3ms/step - loss: 70.8529 - val_loss: 71.1180
Epoch 75/100
23/23 [==============================] - 0s 3ms/step - loss: 68.9101 - val_loss: 68.8566
Epoch 76/100
23/23 [==============================] - 0s 3ms/step - loss: 67.6902 - val_loss: 68.4389
Epoch 77/100
23/23 [==============================] - 0s 3ms/step - loss: 66.3028 - val_loss: 66.2143
Epoch 78/100
23/23 [==============================] - 0s 3ms/step - loss: 64.7241 - val_loss: 65.3887
Epoch 79/100
23/23 [==============================] - 0s 3ms/step - loss: 63.8723 - val_loss: 63.9580
Epoch 80/100
23/23 [==============================] - 0s 3ms/step - loss: 62.9006 - val_loss: 62.6776
Epoch 81/100
23/23 [==============================] - 0s 3ms/step - loss: 61.3477 - val_loss: 64.0454
Epoch 82/100
23/23 [==============================] - 0s 3ms/step - loss: 60.8844 - val_loss: 60.8377
Epoch 83/100
23/23 [==============================] - 0s 3ms/step - loss: 59.9788 - val_loss: 60.1007
Epoch 84/100
23/23 [==============================] - 0s 3ms/step - loss: 58.9167 - val_loss: 58.8995
Epoch 85/100
23/23 [==============================] - 0s 3ms/step - loss: 57.6954 - val_loss: 58.0480
Epoch 86/100
23/23 [==============================] - 0s 3ms/step - loss: 56.8462 - val_loss: 58.0000
Epoch 87/100
23/23 [==============================] - 0s 3ms/step - loss: 55.8096 - val_loss: 56.9527
Epoch 88/100
23/23 [==============================] - 0s 3ms/step - loss: 56.1275 - val_loss: 55.9753
Epoch 89/100
23/23 [==============================] - 0s 3ms/step - loss: 54.3824 - val_loss: 55.0344
Epoch 90/100
23/23 [==============================] - 0s 3ms/step - loss: 53.3904 - val_loss: 53.9431
Epoch 91/100
23/23 [==============================] - 0s 3ms/step - loss: 52.7854 - val_loss: 53.3555
Epoch 92/100
23/23 [==============================] - 0s 3ms/step - loss: 51.8527 - val_loss: 52.8638
Epoch 93/100
23/23 [==============================] - 0s 3ms/step - loss: 51.2126 - val_loss: 52.4101
Epoch 94/100
23/23 [==============================] - 0s 3ms/step - loss: 50.5853 - val_loss: 51.8525
Epoch 95/100
23/23 [==============================] - 0s 3ms/step - loss: 50.1946 - val_loss: 51.2015
Epoch 96/100
23/23 [==============================] - 0s 3ms/step - loss: 49.6214 - val_loss: 51.2086
Epoch 97/100
23/23 [==============================] - 0s 3ms/step - loss: 48.8751 - val_loss: 51.8932
Epoch 98/100
23/23 [==============================] - 0s 3ms/step - loss: 48.9772 - val_loss: 50.4756
Epoch 99/100
23/23 [==============================] - 0s 3ms/step - loss: 47.9034 - val_loss: 49.8108
Epoch 100/100
23/23 [==============================] - 0s 3ms/step - loss: 47.1903 - val_loss: 50.0800

In [17]:
from sklearn.metrics import mean_squared_error
y_predict = model.predict(x_val)

#Evaluating the model
scores = mean_squared_error(y_val, y_predict)
print("Mean squared error: {}".format(scores))

Mean squared error: 50.0799632044237